# Generated by Django 5.2 on 2026-06-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vote_voteoption_uservote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system_task_created', 'Tạo task'), ('system_task_updated', 'Cập nhật task'), ('system_task_assigned', 'Assign task'), ('system_task_deleted', 'Xóa task'), ('system_member_added', 'Thêm thành viên'), ('system_member_left', 'Rời nhóm'), ('system_member_kicked', 'Bị kick'), ('system_admin_transferred', 'Chuyển admin'), ('system_name_changed', 'Đổi tên nhóm'), ('system_avatar_changed', 'Đổi avatar nhóm'), ('system_vote_created', 'Tạo vote nhóm'), ('system_vote_deleted', 'Xóa vote nhóm'), ('system_vote_updated', 'Cập nhật vote nhóm'), ('system_vote_option_added', 'Thêm option vote nhóm'), ('system_vote_option_deleted', 'Xóa option vote nhóm'), ('system_vote_added', 'Người dùng thêm vote nhóm')], default='text', max_length=50),
        ),
    ]
