# Generated by Django 5.2 on 2026-05-28 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='api_post_user_id_b4658e_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'privacy', '-is_pinned', '-created_at'], name='api_post_user_id_5fe609_idx'),
        ),
    ]
