# Generated by Django 5.2 on 2026-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
