# Generated by Django 5.2 on 2026-06-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_messageattachment_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='public_id',
        ),
    ]
