# Generated by Django 5.2.4 on 2025-08-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_name_pendingprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='postarticle',
            name='content',
            field=models.CharField(default='No content', max_length=5000),
        ),
    ]
