# Generated by Django 5.2.4 on 2025-08-18 18:53

import api.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_photo_postarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=api.models.vi_slugify, unique_with=('created_at',)),
        ),
        migrations.AlterField(
            model_name='postarticle',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=api.models.vi_slugify, unique_with=('created_at',)),
        ),
    ]
