# Generated by Django 5.2 on 2026-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_postreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_public',
            field=models.BooleanField(default=False),
        ),
    ]
