# Generated by Django 5.2.4 on 2025-08-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
