# Generated by Django 5.2 on 2026-06-03 11:25

import api.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postshare',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postshare',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pendingprofile',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[api.models.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='pendingprofile',
            name='first_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Tên chỉ được chứa chữ cái và khoảng trắng', regex='^[a-zA-ZÀ-ỹ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='pendingprofile',
            name='last_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Tên chỉ được chứa chữ cái và khoảng trắng', regex='^[a-zA-ZÀ-ỹ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[api.models.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Tên chỉ được chứa chữ cái và khoảng trắng', regex='^[a-zA-ZÀ-ỹ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Tên chỉ được chứa chữ cái và khoảng trắng', regex='^[a-zA-ZÀ-ỹ\\s]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('post', 'user')},
        ),
    ]
