# Generated by Django 5.2 on 2026-06-25 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_videoroom_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Hoàn thành'), ('missed', 'Cuộc gọi nhỡ'), ('declined', 'Từ chối')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='videoroom',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videoroom',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system_task_created', 'Tạo task'), ('system_task_updated', 'Cập nhật task'), ('system_task_assigned', 'Assign task'), ('system_task_deleted', 'Xóa task'), ('system_member_added', 'Thêm thành viên'), ('system_member_left', 'Rời nhóm'), ('system_member_kicked', 'Bị kick'), ('system_admin_transferred', 'Chuyển admin'), ('system_name_changed', 'Đổi tên nhóm'), ('system_avatar_changed', 'Đổi avatar nhóm'), ('system_vote_created', 'Tạo vote nhóm'), ('system_vote_deleted', 'Xóa vote nhóm'), ('system_vote_updated', 'Cập nhật vote nhóm'), ('system_vote_option_added', 'Thêm option vote nhóm'), ('system_vote_option_deleted', 'Xóa option vote nhóm'), ('system_vote_added', 'Người dùng thêm vote nhóm'), ('system_call_completed', 'Cuộc gọi hoàn thành'), ('system_call_missed', 'Cuộc gọi nhỡ'), ('system_call_declined', 'Cuộc gọi bị từ chối')], default='text', max_length=50),
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chưa trả lời'), ('accepted', 'Đã bắt máy'), ('declined', 'Từ chối'), ('missed', 'Nhỡ')], default='pending', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.videoroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
