# Generated by Django 5.2 on 2026-06-03 11:39

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_postshare_deleted_postshare_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
