# Generated by Django 5.2 on 2026-06-25 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_videoroom_end_reason_videoroom_ended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Hoàn thành'), ('missed', 'Cuộc gọi nhỡ'), ('declined', 'Từ chối'), ('cancelled', 'Huỷ')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='videoroom',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoroom',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['room', 'status'], name='api_callpar_room_id_52d6f5_idx'),
        ),
    ]
