# Generated by Django 5.2.4 on 2025-08-20 19:34

import api.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=api.models.vi_slugify, unique=True),
        ),
    ]
