# Generated by Django 5.2 on 2026-06-06 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_message_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationmember',
            name='api_convers_is_perm_932850_idx',
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'is_permanently_hidden'], name='api_convers_user_id_4a3be8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['reciever', 'is_read'], name='api_notific_recieve_794789_idx'),
        ),
    ]
