# Generated by Django 5.2.4 on 2025-08-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_postarticle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
