# Generated by Django 5.2 on 2026-06-27 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_videoroom_end_reason_alter_videoroom_ended_at_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system_task_created', 'Tạo task'), ('system_task_updated', 'Cập nhật task'), ('system_task_assigned', 'Assign task'), ('system_task_deleted', 'Xóa task'), ('system_member_added', 'Thêm thành viên'), ('system_member_left', 'Rời nhóm'), ('system_member_kicked', 'Bị kick'), ('system_admin_transferred', 'Chuyển admin'), ('system_name_changed', 'Đổi tên nhóm'), ('system_avatar_changed', 'Đổi avatar nhóm'), ('system_vote_created', 'Tạo vote nhóm'), ('system_vote_deleted', 'Xóa vote nhóm'), ('system_vote_updated', 'Cập nhật vote nhóm'), ('system_vote_option_added', 'Thêm option vote nhóm'), ('system_vote_option_deleted', 'Xóa option vote nhóm'), ('system_vote_added', 'Người dùng thêm vote nhóm'), ('system_call_completed', 'Cuộc gọi hoàn thành'), ('system_call_missed', 'Cuộc gọi nhỡ'), ('system_call_declined', 'Cuộc gọi bị từ chối'), ('system_call_cancelled', 'Cuộc gọi video bị huỷ')], default='text', max_length=50),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accept', 'Tham gia'), ('Decline', 'Từ chối'), ('Pending', 'Chưa phản hồi')], default='Pending', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['content_type', 'object_id', 'celery_task_id'], name='api_event_content_c147c6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['content_type', 'object_id', 'created_by'], name='api_event_content_3e8152_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['content_type', 'object_id', 'title'], name='api_event_content_63eb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['content_type', 'object_id', 'start_time'], name='api_event_content_4aad40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
    ]
