# Generated by Django 5.2 on 2026-06-08 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_conversationmember_api_convers_is_perm_932850_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_recieve_794789_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to'], name='api_message_reply_t_5775c2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['reciever', 'is_read', '-created_at'], name='api_notific_recieve_fccdf0_idx'),
        ),
    ]
