# Generated by Django 5.2 on 2026-06-27 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_message_message_type_event_eventparticipant_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='api_event_content_c147c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='api_event_content_3e8152_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='api_event_content_63eb0d_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('accept', 'Tham gia'), ('decline', 'Từ chối'), ('pending', 'Chưa phản hồi')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['content_type', 'object_id'], name='api_event_content_598f3a_idx'),
        ),
    ]
