# Generated by Django 5.2 on 2026-06-10 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_notification_api_notific_recieve_794789_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=250)),
            ],
        ),
        # migrations.AlterUniqueTogether(
        #     name='postreport',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='postreport',
        #     name='post',
        # ),
        # migrations.RemoveField(
        #     model_name='postreport',
        #     name='user',
        # ),
        # migrations.AddField(
        #     model_name='conversation',
        #     name='avatar_url',
        #     field=models.URLField(blank=True, max_length=500, null=True),
        # ),
        # migrations.AddField(
        #     model_name='conversation',
        #     name='create_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='conversation',
        #     name='name',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='conversationmember',
        #     name='role',
        #     field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        # ),
        # migrations.AddIndex(
        #     model_name='conversationmember',
        #     index=models.Index(fields=['conversation', 'user', 'role'], name='api_convers_convers_4c4e24_idx'),
        # ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.DeleteModel(
        #     name='PostReport',
        # ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('comment', 'user'), ('post', 'user')},
        ),
    ]
