# Generated by Django 5.2.4 on 2025-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
