# Generated by Django 5.2 on 2026-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_on_post', 'Comment on Post'), ('reply_on_comment', 'Reply on Comment'), ('tagged_in_reply', 'Tagged in Reply'), ('reaction_on_post', 'Reaction on Post'), ('reaction_on_comment', 'Reaction on Comment'), ('friend_request', 'Friend Request'), ('follow', 'Follow'), ('share_post', 'Share on Post'), ('accepted_friend_request', 'Accept Friend'), ('event_reminder', 'Event Reminder')], max_length=25),
        ),
    ]
