# Generated by Django 5.2 on 2026-07-02 12:20

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối'), ('pending', 'Đang chờ duyệt')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('role', models.CharField(choices=[('owner', 'Chủ group'), ('admin', 'Người kiểm duyệt'), ('member', 'Thành viên')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('approved', 'Đã duyệt'), ('pending', 'Chờ duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system_task_created', 'Tạo task'), ('system_task_updated', 'Cập nhật task'), ('system_task_assigned', 'Assign task'), ('system_task_deleted', 'Xóa task'), ('system_member_added', 'Thêm thành viên'), ('system_member_left', 'Rời nhóm'), ('system_member_kicked', 'Bị kick'), ('system_admin_transferred', 'Chuyển admin'), ('system_name_changed', 'Đổi tên nhóm'), ('system_avatar_changed', 'Đổi avatar nhóm'), ('system_vote_created', 'Tạo vote nhóm'), ('system_vote_deleted', 'Xóa vote nhóm'), ('system_vote_updated', 'Cập nhật vote nhóm'), ('system_vote_option_added', 'Thêm option vote nhóm'), ('system_vote_option_deleted', 'Xóa option vote nhóm'), ('system_vote_added', 'Người dùng thêm vote nhóm'), ('system_call_completed', 'Cuộc gọi hoàn thành'), ('system_call_missed', 'Cuộc gọi nhỡ'), ('system_call_declined', 'Cuộc gọi bị từ chối'), ('system_call_cancelled', 'Cuộc gọi video bị huỷ'), ('system_event_created', 'Tạo sự kiện'), ('system_event_cancelled', 'Xóa sự kiện'), ('system_event_attended', 'Tham gia sự kiện'), ('system_event_updated', 'Cập nhật sự kiện')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_on_post', 'Comment on Post'), ('reply_on_comment', 'Reply on Comment'), ('tagged_in_reply', 'Tagged in Reply'), ('reaction_on_post', 'Reaction on Post'), ('reaction_on_comment', 'Reaction on Comment'), ('friend_request', 'Friend Request'), ('follow', 'Follow'), ('share_post', 'Share on Post'), ('accepted_friend_request', 'Accept Friend'), ('event_reminder', 'Event Reminder'), ('group_request_accepted', 'Accept join request'), ('group_post_accepted', 'Accept post request'), ('group_notification', 'Group important notification')], max_length=25),
        ),
        migrations.AlterField(
            model_name='postshare',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.post'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=api.models.group_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.group'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', 'post_status', 'is_pinned', '-created_at'], name='api_post_group_i_244327_idx'),
        ),
        migrations.AddField(
            model_name='groupdepartment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.group'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.group'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.groupdepartment'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouprole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grouprole'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by', '-created_at'], name='api_group_created_cd63e5_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdepartment',
            index=models.Index(fields=['group'], name='api_groupde_group_i_cc9f0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupdepartment',
            unique_together={('group', 'name')},
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'user', 'status'], name='api_groupjo_group_i_25aa4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='grouprole',
            index=models.Index(fields=['group'], name='api_groupro_group_i_e4fabd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouprole',
            unique_together={('group', 'name')},
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'user', 'is_active'], name='api_groupme_group_i_51b0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'user', 'role'], name='api_groupme_group_i_ba87a5_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'is_active', 'joined_at'], name='api_groupme_group_i_9ce40c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
    ]
