# Generated by Django 5.2 on 2026-07-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_groupdepartment_groupjoinrequest_groupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
