# Generated by Django 5.2.4 on 2025-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_comment_deleted_comment_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AlterField(
            model_name='log',
            name='logtext',
            field=models.TextField(),
        ),
    ]
