# Generated by Django 5.2 on 2026-07-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_group_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_members', to='api.groupdepartment'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_role_members', to='api.grouprole'),
        ),
    ]
