# Generated by Django 5.2.4 on 2025-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_log_user_alter_log_logtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='logtext',
        ),
        migrations.AddField(
            model_name='log',
            name='metadata_json',
            field=models.TextField(blank=True, default='{}', help_text='Lưu trữ metadata (dictionary) từ activity stream dưới dạng chuỗi JSON đã serialize.', null=True),
        ),
    ]
