# Generated by Django 5.2 on 2026-07-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_groupmember_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='department',
        ),
        migrations.AddField(
            model_name='grouprole',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='api.groupdepartment'),
        ),
    ]
