# Generated by Django 5.2.4 on 2025-11-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_log_logtext_log_metadata_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='metadata_json',
            field=models.TextField(blank=True, help_text='Lưu trữ metadata (dictionary) từ activity stream dưới dạng chuỗi JSON đã serialize.', null=True),
        ),
    ]
