# Generated by Django 5.2 on 2026-07-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_groupmember_department_grouprole_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to='api.groupdepartment'),
        ),
    ]
