# Generated by Django 5.2.4 on 2025-12-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_log_metadata_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='AddFriendRequest',
        ),
    ]
