# Generated by Django 5.2.4 on 2025-12-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_profile_friends_delete_addfriendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20),
        ),
    ]
