# Generated by Django 5.2 on 2026-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_on_post', 'Comment on Post'), ('reply_on_comment', 'Reply on Comment'), ('tagged_in_reply', 'Tagged in Reply'), ('reaction_on_post', 'Reaction on Post'), ('reaction_on_comment', 'Reaction on Comment'), ('friend_request', 'Friend Request'), ('follow', 'Follow'), ('share_post', 'Share on Post'), ('accepted_friend_request', 'Accept Friend'), ('event_reminder', 'Event Reminder'), ('group_request_accepted', 'Accept join request'), ('group_post_accepted', 'Accept post request'), ('group_post_declined', 'Decline post request'), ('group_notification', 'Group important notification'), ('group_admin_added', 'Transfer admin group'), ('group_owner_transfer', 'Transfer admin group')], max_length=25),
        ),
    ]
