# Generated by Django 5.2.4 on 2025-12-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_conversation_message_messageattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.message'),
        ),
        migrations.DeleteModel(
            name='MessageRead',
        ),
    ]
