# Generated by Django 5.2.4 on 2026-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_conversationmember_last_read_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerequest',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
