# Generated by Django 5.2.4 on 2026-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_messagerequest_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='MessageRequest',
        ),
    ]
