# Generated by Django 5.2 on 2026-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
