# Generated by Django 5.2 on 2026-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_groupsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupjoinrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
