# Generated by Django 5.2 on 2026-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_reviewed_at_to_groupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_post_privacy',
            field=models.CharField(choices=[('public', 'Công khai'), ('friends', 'Bạn bè'), ('private', 'Chỉ mình tôi')], default='public', max_length=15),
        ),
    ]
