# Generated by Django 5.2 on 2026-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_notification_event_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
