# Generated by Django 6.0.3 on 2026-03-31 10:04

import api.models
import autoslug.fields
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postarticle',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=api.models.vi_slugify),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='api_convers_updated_4bdcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='api_convers_status_115742_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='api_message_sender__7d2c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['actor'], name='api_notific_actor_i_479205_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='api_profile_user_id_bc09a5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-created_at'], name='api_profile_created_de4dc8_idx'),
        ),
    ]
