# Generated by Django 5.2 on 2026-07-28 07:00

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_notification_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa trả lời'), ('accepted', 'Đã bắt máy'), ('declined', 'Từ chối'), ('missed', 'Nhỡ'), ('left', 'Đã rời')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=api.models.post_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv', 'webm'])])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post'], name='api_postvid_post_id_7d8f4d_idx')],
            },
        ),
    ]
