# Generated by Django 5.2 on 2026-07-28 07:25

import api.models
import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_callparticipant_status_postvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=api.models.post_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=api.models.post_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv', 'webm'])]),
        ),
    ]
