# Generated by Django 6.0.3 on 2026-03-31 13:43

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_messageattachment_file_alter_postphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to=api.models.chat_upload_path),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.post_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
