# Generated by Django 6.0.3 on 2026-04-08 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_post_api_post_title_915672_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='api_searchh_content_1f5327_idx',
        ),
        migrations.AlterField(
            model_name='postarticle',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_group'], name='api_convers_is_grou_c346a4_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user'], name='api_fcmtoke_user_id_c44027_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='api_message_message_976524_idx'),
        ),
        migrations.AddIndex(
            model_name='postarticle',
            index=models.Index(fields=['user'], name='api_postart_user_id_4b9945_idx'),
        ),
        migrations.AddIndex(
            model_name='postarticle',
            index=models.Index(fields=['title'], name='api_postart_title_fda64d_idx'),
        ),
        migrations.AddIndex(
            model_name='postphoto',
            index=models.Index(fields=['post'], name='api_postpho_post_id_64af6c_idx'),
        ),
    ]
