# Generated by Django 6.0.3 on 2026-04-28 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_comment_is_pinned_comment_tagged_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_on_post', 'Comment on Post'), ('reply_on_comment', 'Reply on Comment'), ('tagged_in_reply', 'Tagged in Reply'), ('reaction_on_post', 'Reaction on Post'), ('reaction_on_comment', 'Reaction on Comment'), ('friend_request', 'Friend Request'), ('follow', 'Follow')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', '-is_pinned', '-created_at'], name='api_comment_post_id_05e96d_idx'),
        ),
    ]
