# Generated by Django 6.0.3 on 2026-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
