# Generated by Django 6.0.3 on 2026-05-04 08:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_notification_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_code',
            field=models.CharField(default=api.models.generate_shared_code, editable=False, max_length=10, unique=True),
        ),
    ]
