# Generated by Django 6.0.3 on 2026-05-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_post_api_post_share_c_4ae867_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
