# Generated by Django 6.0.3 on 2026-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_conversationmember_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmember',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='deleted_at_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
