# Generated by Django 6.0.3 on 2026-05-05 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_conversationmember_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmember',
            name='deleted_at_id',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='deleted_before_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.message'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'user'], name='api_convers_convers_0b1c15_idx'),
        ),
    ]
