# Generated by Django 6.0.3 on 2026-05-05 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_conversationmember_deleted_at_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationmember',
            name='api_convers_convers_3d9c93_idx',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='deleted_at_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['conversation', 'is_hidden'], name='api_convers_convers_8709c8_idx'),
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='deleted_before_message',
        ),
    ]
