# Generated by Django 6.0.3 on 2026-05-05 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_conversationmember_api_convers_convers_3d9c93_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='is_permanently_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['is_permanently_hidden'], name='api_convers_is_perm_932850_idx'),
        ),
    ]
