# Generated by Django 6.0.3 on 2026-05-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_conversationmember_is_permanently_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmember',
            name='last_read_message',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
