# Generated by Django 6.0.3 on 2026-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Công khai'), ('friends', 'Bạn bè'), ('private', 'Chỉ mình tôi')], default='public', max_length=15),
        ),
    ]
