# Generated by Django 6.0.3 on 2026-05-12 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_post_privacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'privacy'], name='api_post_user_id_b4658e_idx'),
        ),
        migrations.AddField(
            model_name='postshare',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.post'),
        ),
        migrations.AddField(
            model_name='postshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['post'], name='api_postsha_post_id_d8aa8d_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['user'], name='api_postsha_user_id_dce6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['-created_at'], name='api_postsha_created_906a58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postshare',
            unique_together={('post', 'user')},
        ),
    ]
