# Generated by Django 6.0.3 on 2026-05-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_postshare_post_api_post_user_id_b4658e_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postshare',
            unique_together=set(),
        ),
    ]
