# Generated by Django 6.0.3 on 2026-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_postshare_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='postshare',
            name='privacy',
            field=models.CharField(choices=[('public', 'Công khai'), ('friends', 'Bạn bè'), ('private', 'Chỉ mình tôi')], default='public', max_length=15),
        ),
    ]
