# Generated by Django 5.2.4 on 2025-12-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
