networks:
  prod-network:
    driver: bridge # bridge dùng để các container gọi nhau qua tên ở mạng nội bộ và cô lập mạng bên ngoài để bảo mật

#ổ đĩa để xóa container không mất data
volumes:
  percona_data:
    external: true # voulums có sẵn và chỉ dùng
  esdata:
    external: true
  # tự tạo volumes lần chạy đầu tiên
  redis-data:
  static-files:
  logs-data:
  backups-data:
  frontend-static:

services:

  percona:
    image: percona/percona-server:8.4 # tải bản 8.4
    container_name: percona
    restart: unless-stopped # tự khởi động nếu bị lỗi
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    deploy: #giới hạn cpu ram cho container
      resources:
        limits:
          cpus: '2' # giới hạn cpu
          memory: 4g # giới hạn ram
        reservations:
          memory: 1g # ram tối thiểu docker luôn có cho container
    volumes:
      - percona_data:/var/lib/mysql # gán ổ đĩa vĩnh viễn
    networks:
      - prod-network # tham gia mạng nội bộ
    ports:
      - "127.0.0.1:3306:3306" #cổng nội bộ chỉ máy gốc mới vào đc
    healthcheck: # kiểm tra sức khỏe 10s 1 lần và không phản hồi sau 5s là lỗi, lỗi 5 lần là unhealthy
      test: ["CMD", "mysqladmin", "ping",
             "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true # yêu cầu bảo mật
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx1g #giơi hạn ram
    deploy: # giới hạn cpu ram cho container
      resources:
        limits:
          cpus: '2'
          memory: 1500m
        reservations:
          memory: 512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - prod-network
    ports:
      - "127.0.0.1:9200:9200" #cổng nội bộ chỉ máy gốc mới vào đc
    healthcheck:
      test: ["CMD-SHELL",
             "curl -sf -u elastic:${ELASTIC_PASSWORD} http://127.0.0.1:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1200m  # maxmemory 1gb + overhead
        reservations:
          memory: 128m
    command: > # yêu cầu pass, giới hạn ram và khi đầy sẽ tự xóa 
      redis-server
      --requirepass ${REDIS_PASSWORD}  
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru 
      --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - prod-network
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
# ─── Nginx ───────────────────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64m
        reservations:
          memory: 32m
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:80:80" # khi cloudflare gọi nginx, nó gọi nội bộ từ máy này nên vẫn truy cập đc
    networks:
      - prod-network
    depends_on:
      frontend:
        condition: service_healthy
      django:
        condition: service_healthy

  # ─── Frontend (Django app, static serve qua whitenoise) ──
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend
    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300m
        reservations:
          memory: 128m

    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      exec granian --interface asgi --host 0.0.0.0 --port 8000 --workers 2 --runtime-threads 4 --backlog 1024 --http 1 frontend.asgi:application
      "
    volumes:
      - frontend-static:/app/staticfiles
      - logs-data:/app/logs

    ports:
      - "127.0.0.1:8080:8000"

    networks:
      - prod-network

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # ─── Django ──────────────────────────────────────────
  django:
    build:
      context: ./backend # Dockerfile nằm trong thư mục backend
      dockerfile: Dockerfile
    container_name: django
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 800m
        reservations:
          memory: 256m
    env_file:
      - ./backend/.env # nạp file env vào
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      exec granian --interface asgi --host 0.0.0.0 --port 8000 --workers 3 --runtime-threads 6 --backlog 2048 --http 1 backend.asgi:application
      "
    volumes:
      - static-files:/app/staticfiles # Nơi Django đẩy file tĩnh ra ngoài sau lệnh collectstatic
      - logs-data:/app/logs # sau dấu : tức là đem vào app/logs trong container 
    networks:
      - prod-network
    depends_on:
      percona:
        condition: service_healthy # Django chỉ khởi động khi MySQL ĐÃ THỰC SỰ KHỎE MẠNH (pass qua vòng healthcheck)
      elasticsearch:
        condition: service_healthy # Django chỉ khởi động khi Elasticsearch ĐÃ THỰC SỰ KHỎE MẠNH
      redis:
        condition: service_healthy # Django chỉ khởi động khi redis ĐÃ THỰC SỰ KHỎE MẠNH
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ─── Celery Worker ───────────────────────────────────
  celery-worker: # khối celery xử lý chung tất cả
    build:
      context: ./backend # Dockerfile nằm trong thư mục backend
      dockerfile: Dockerfile
    container_name: celery-worker
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 400m
        reservations:
          memory: 128m
    command: celery -A backend worker -Q celery --loglevel=info --concurrency=4
    env_file:
      - ./backend/.env
    volumes:
      - logs-data:/app/logs
      - backups-data:/app/backups
    networks:
      - prod-network
    depends_on:
      django:
        condition: service_healthy

  celery-worker-notifications: #khối chỉ xử lý notification
    build:
      context: ./backend # Dockerfile nằm trong thư mục backend
      dockerfile: Dockerfile
    container_name: celery-worker-notifications
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256m
        reservations:
          memory: 64m
    command: celery -A backend worker -Q notifications --loglevel=info --concurrency=2
    env_file:
      - ./backend/.env
    volumes:
      - logs-data:/app/logs
      - backups-data:/app/backups
    networks:
      - prod-network
    depends_on:
      django:
        condition: service_healthy

  celery-worker-emails: #khối chỉ xử lý email
    build:
      context: ./backend # Dockerfile nằm trong thư mục backend
      dockerfile: Dockerfile
    container_name: celery-worker-emails
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256m
        reservations:
          memory: 64m
    command: celery -A backend worker -Q emails --loglevel=info --concurrency=2
    env_file:
      - ./backend/.env
    volumes:
      - logs-data:/app/logs
      - backups-data:/app/backups
    networks:
      - prod-network
    depends_on:
      django:
        condition: service_healthy

  # ─── Celery Beat ─────────────────────────────────────
  celery-beat: # chịu trách nhiệm kích hoạt worker khi tới lịch
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery-beat
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128m
        reservations:
          memory: 64m
    command: celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./backend/.env
    volumes:
      - logs-data:/app/logs
    networks:
      - prod-network
    depends_on:
      django:
        condition: service_healthy