"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iid499j8r0iwy3_7^23oe4oq-u4s+shd!xyyc9qnnce7^3qwc7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



INSTALLED_APPS = [
    'jazzmin',  #giao diện admin 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'socialnetwork', #app
    # 'cacheops' # lưu các truy vấn đã truy vấn và trả về luôn, save tài nguyên
    'django_extensions',# công cụ tiện ích 
    'debug_toolbar',#hiển thị các tiến trình
    'silk', #theo dõi sâu
]

MIDDLEWARE = [

    'debug_toolbar.middleware.DebugToolbarMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "silk.middleware.SilkyMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "SocialNetwork",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",   
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'",
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ 
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT=os.path.join(BASE_DIR,'network','media')
MEDIA_URL='/media/'
#==========================================================================================================================================

#tùy chỉnh jazz min
JAZZMIN_SETTINGS = {
    "site_title": "SOCIAL NETWORK ADMIN",
    "site_header": "SOCIAL NETWORK",
    "site_brand": "SOCIAL NETWORK",
    "site_logo": "images/logo-white.png",
    "login_logo": "images/logo-white.png",
    "login_logo_dark": "images/logo-white.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "images/favicon.png",  # favicon
    "welcome_sign": "👋 Welcome to Social Admin Dashboard",
    "copyright": "© 2025 Social Co.",
    "search_model": ["auth.User", "socialnetwork.Post"],

    "user_avatar": "profile.picture",

    "topmenu_links": [
        {"name": "🏠 Home", "url": "/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "socialnetwork"},
        {"name": "💬 Support", "url": "https://t.me/yourchannel", "new_window": True},
    ],

    "usermenu_links": [
        {"name": "Documentation", "url": "https://docs.djangoproject.com/", "new_window": True},
        {"model": "auth.user"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "socialnetwork"],

    "custom_links": {
        "socialnetwork": [
            {
                "name": "📊 Thống kê",
                "url": "admin/socialnetwork/post/",
                "icon": "fas fa-chart-line",
                "permissions": ["socialnetwork.view_post"]
            },
            {
                "name": "📁 Tải dữ liệu",
                "url": "/admin/socialnetwork/post/export/",
                "icon": "fas fa-download",
            },
        ]
    },

    "icons": {
        "auth": "fas fa-users",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users-cog",
        "socialnetwork.post": "fas fa-photo-video",
        "socialnetwork.comment": "fas fa-comments",
        "socialnetwork.profile": "fas fa-id-badge",
    },

    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",  # tab
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "socialnetwork.profile": "carousel",
    },

    "language_chooser": True,

    # Footer links
    "show_ui_builder": True,
}
JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",  # "darkly", "superhero", "lux" cũng đẹp
    "accent": "accent-pink",
    "navbar": "navbar-dark bg-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_disable_expand": False,
    "actions_sticky_top": True,
    "small_text": "md",
    "brand_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "button_classes": {
        "primary": "btn btn-outline-warning",
        "secondary": "btn btn-outline-light",
    },
}

#======================================================================

#cấu hình cacheops
# CACHEOPS_REDIS={
#     'host':'localhost',
#     'port':'6379',
#     'db':1,
#     'socket_timeout':3,
# }

# CACHEOPS={
#     'socialnework.*':{'ops':'all', 'timeout':60*15},# ở tất cả bảng, cache(lưu vào bộ nhớ phụ và reuse) ví dụ get,filter,count...trong 15p. Muốn 1 bảng cố định thì 'socialnetwork.tên bảng'
#     'auth.user':{'ops':('get','filter'),'timeout':60*60} # cache user từ auth, ví dụ cache khi lấy ra user, lọc user
# }

#==========================================================================

#Cấu hình tool bar
# MIDDLEWARE = [
#     ...
#     'debug_toolbar.middleware.DebugToolbarMiddleware',
# ] 

INTERNAL_IPS = [ # xem ip nào đc xem toolbar 
    "127.0.0.1",
]

# if settings.DEBUG: urls.py
#     import debug_toolbar
#     urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]