# Generated by Django 5.2.4 on 2025-07-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
