# Generated by Django 5.2.4 on 2025-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_alter_post_post_id_alter_post_slug_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='socialnetwork.profile'),
        ),
    ]
